  [[main]]
    identifier = "about"
    name       = "About"
    pageRef    = "/about"
  [[main]]
    identifier = "projects"
    name       = "Projects"
    pageRef    = "/projects"
  [[main]]
    identifier = "artilcles"
    name       = "Resources"
    pageRef    = "/resources"


  [[main]]
    identifier = "alt-kaboom"
    name       = "Alt-Kaboom"
    pageRef    = "/projects/alt-kaboom.html"
    parent     = "projects"
  [[main]]
    identifier = "bad-donkey"
    name       = "Bad-Donkey"
    pageRef    = "/projects/bad-donkey.html"
    parent     = "projects"
  [[main]]
    identifier = "decentral-practices"
    name       = "Decentralized Best Practices"
    pageRef    = "/projects/decentralized-best-practices.html"
    parent     = "projects"
 [[main]]
    identifier = "decentral-domains"
    name       = "Decentralized Domains"
    pageRef    = "/projects/decentralized-domains.html"
    parent     = "projects"